name = "RCallSFBridge"
uuid = "f9c30e78-1131-43b7-9414-29219ebe78a3"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
GeoFormatTypes = "0.4"
RCall = "0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
